# Generated by Django 4.0.1 on 2022-01-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='liked_by',
        ),
    ]
