# Generated by Django 4.0.1 on 2022-01-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_status_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='file',
        ),
    ]
